[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "8wYf5J2kissG8LYmmZpBZZWFGPGTZuUX5Y7Cnc3Zt5AT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/kristen/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
